#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# Displays FizzBuzz, Fizz or Buzz
e=1
while [ $e -le 100 ]
do
        if [ $((e % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((e % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((e % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$e"
	fi
	((e++)) 
done
