#!/usr/bin/env bash
# This script is displaying "Best School" on new lines,it's good luck for 8 and bad for 4 

a=1
while [ $a -le 10 ]
do
        if [ $a == 4 ]
	then
		echo "bad luck"
	elif [ $a == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
        ((a++))
done
