#!/usr/bin/env bash
# This script is displaying 1 to 20
# displays 4 and then bad luck form China
# displays 9 and then bad luck from Japan 
# displays 17 and then bad luck from Italy 
e=1
while [ $e -le 20 ]
do
        echo "$e"
	case $e in
	4)
	echo "bad luck from China"
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
	;;
	esac
        ((e++))
done
